apiVersion: v1
kind: Service
metadata:
    name: mygoweb
    namespace: development
    spec:
        ports:
            - port: 80
                  targetPort: 8080
                      selector:
                            app: mygoweb
